### ISSUE TITLE
browsersync settings cannot be configured through gulpfile.overrides

### ISSUE THREAD

**Issue by ole1986** [conterra/mapapps-4-developers#16]
Since I am on vscode and of course using `git.autofetch` I noticed that on every git fetch of my submodules (being located in `src/main/js/bundles/my_git_submodule_bundle`) caused browsersync to full reload the page.

Reason for it is the `.git/FETCH_HEAD` being "touched" by the autofetch process.

So I added a `gulpfile.overrides.js` but unfortunately noticed I cannot modify the option "directories" in it. I had to to this in gulpfile.js

-- 

Also, I am little concerned about the implementation of browsersync since it always does a full page reload. Even when changing small pieces in source code of a bundle

**Comment by ole1986** [comment]
I workaround this using 

`copyIgnore: "**/*.{vue,ts,js,git}",` in the gulpfile.js

**Comment by jessebluemr** [comment]
Hello,

thanks for your report.

The page reload of browser sync is triggered in the [watchFinishedReceiver](https://github.com/conterra/mapapps-4-developers/blob/d0171df9b438bfe53e280ec1ab90c4e2c0637319/gulpfile.js#L71).

The reload can be disabled by creating a gulpfile.overrides.js with [autoReload:false](https://github.com/conterra/mapapps-4-developers/blob/d0171df9b438bfe53e280ec1ab90c4e2c0637319/gulpfile.overrides-sample.js#L21).

The full page reload is triggered when ever a build is finished.
Currently there is no hot reloading possible, so yes every small code change refreshes the page.

If you like to have more options in the gulpfile.overrides.js or your workarround integrated as default in mapapps-4-developers, then feel free to create a pull request.
