### ISSUE TITLE
Rollup doesn't start with identity service configuration

### ISSUE THREAD

**Issue by MrMufflon** [conterra/mapapps-4-developers#22]
I made changes to my config to use our identity service in our dev-project. But rollup doesn't seem to start correctly. It doesn't serve the files anymore. My requests get timed out. There are no logs. When i change my config to the default everything works.

`[INFO] [15:26:00] Starting 'browser-sync'...
[INFO] [15:26:00] [jsreg] Import of bundles from '/home/felix/code/ORKA/orka-js/node_modules/' took:53msec
[INFO] [15:26:00] [jsreg] Import of bundles from 'target/webapp/js' took:51msec
[INFO] [15:26:00] [jsreg] Import of bundles from 'target/bundle-imports/' took:185msec
[INFO] [15:26:00] [jsreg] Imported 234 bundles in 194msec
[INFO] [15:26:00] Options:  {
[INFO]   'mapapps.remote.base': '.',
[INFO]   'client.config.productname': 'mapapps-4-developers',
[INFO]   'apprt.version': '4.15.1',
[INFO]   'client.config.initjs': '${mapapps.remote.base}/resources/jsregistry/root/apprt-boot/${apprt.version}/boot.js',
[INFO]   'client.config.mainlayerfiles': 'apprt/launch/layer',
[INFO]   'default.app.name': 'orka',
[INFO]   'proxy.allowedServerUrls': '*://*:*/**;',
[INFO]   'proxy.use.rules': '',
[INFO]   'cors.request.trustedServers': [ '${mapapps.remote.base}', 'https://dev0431l.conterra.de' ],
[INFO]   'client.config.logging': 'DEBUG',
[INFO]   'security.login.base': 'https://dev0431l.conterra.de/identity',
[INFO]   'security.login.service.url': '${security.login.base}/account/login',
[INFO]   'security.logout.service.url': '${security.login.base}/account/logout',
[INFO]   'security.self.service.url': '${security.login.base}/account/self',
[INFO]   'security.identity.tokens.service.url': '${security.login.base}/account/tokens',
[INFO]   'security.identity.self.service.url': '${security.self.service.url}',
[INFO]   'security.mode': 'IDENTITY',
[INFO]   'security.identity.cookieName': 'ctIDENTITY',
[INFO]   'jsregistry.directoryscanner.npmfolder': '/home/felix/code/ORKA/orka-js/node_modules',
[INFO]   'jsregistry.directoryscanner.npmincludes': 'mocha,chai,@conterra,@conterra/mapapps-mocha-runner,@types/mocha,@types/chai,@vue,@vue/test-utils,vue-template-compiler'
[INFO] }
[INFO] [Browsersync] Access URLs:
[INFO]  ---------------------------------------
[INFO]        Local: https://localhost:8443
[INFO]     External: https://192.168.1.109:8443
[INFO]  ---------------------------------------
[INFO]           UI: http://localhost:3001
[INFO]  UI External: http://localhost:3001
[INFO]  ---------------------------------------
[INFO] [Browsersync] Serving files from: ./target/webapp
[INFO] [Browsersync] Serving files from: ./target/test-classes`

**Comment by jessebluemr** [comment]
The observed error was a problem of ct-mapapps-browsersync.
In the "dev" branch of mapapps-4-developers a newer version is already configured.

You can upgrade your mapapps-4-developers project with ct-mapapps-browsersync 0.0.35 then this error is gone.
The error source are duplicated keys in your application.properties.
