### ISSUE TITLE
Browsersinc does not start if the property "https" was configured with a certificate object

### ISSUE THREAD

**Issue by ChristophMaskos** [conterra/mapapps-4-developers#23]
Hello, 
the following configuration in gulpfile.overrides.js causes Browsersinc to no longer start:

```
https: {
       key: "src/main/config/file.key",
       cert: "src/main/config/file.cer"
 }
```
(https://browsersync.io/docs/options#option-https)

Gulp is running and the startup process always stops after the options part. No exceptions or error messages.

```
[INFO] [08:14:31] Options:  {
[INFO]   'mapapps.remote.base': '.',
[INFO]   'client.config.productname': 'mapapps-4-developers',
[INFO]   'apprt.version': '4.16.0',
[INFO]   'client.config.initjs': '${mapapps.remote.base}/resources/jsregistry/root/apprt-boot/${apprt.version}/boot.js',
[INFO]   'client.config.mainlayerfiles': 'apprt/launch/layer',
[INFO]   'default.app.name': 'Demo',
[INFO]   'proxy.allowedServerUrls': '*://*:*/**;',
[INFO]   'proxy.use.rules': '',
[INFO]   'cors.request.trustedServers': '${mapapps.remote.base}',
[INFO]   'client.config.logging': 'DEBUG',
[INFO]   'security.login.base': '${mapapps.remote.base}',
[INFO]   'security.login.service.url': '${security.login.base}/account/login',
[INFO]   'security.logout.service.url': '${security.login.base}/account/logout',
[INFO]   'security.self.service.url': '${security.login.base}/account/self',
[INFO]   'security.identity.tokens.service.url': '${security.login.base}/account/tokens',
[INFO]   'security.identity.self.service.url': '${security.self.service.url}'
[INFO] }
```
What am I doing wrong or what have I forgotten?

**Comment by jessebluemr** [comment]
Thanks for reporting the issue.

I tried to reproduce the problem, but can't.
Can you provide more details to reproduce the issues?

Is it working if you set https to true? Then a self signed certficate is created automatically.

gulpfile.overrides.js:

```js
module.exports = {
    https: true
};
```

Here my configuration with a custom certificate:

gulpfile.overrides.js:

```js
module.exports = {
    https: {
        key: "src/main/config/key.pem",
        cert: "src/main/config/cert.pem"
    }
};
```

the key and pem files are asccii representations of the private key and certificate:

cert.pem:
```plain
-----BEGIN CERTIFICATE-----
base64...
-----END CERTIFICATE-----
```

key.pem:
```plain
-----BEGIN PRIVATE KEY-----
base64...
-----END PRIVATE KEY-----
```

**Comment by ChristophMaskos** [comment]
> Thanks for reporting the issue.
> 
> I tried to reproduce the problem, but can't. Can you provide more details to reproduce the issues?
> 
> Is it working if you set https to true? Then a self signed certficate is created automatically.
> 

Thanks for the quick reply. The error was in the cert and key files. It would be nice if an error message appeared in the console in this case.
